model_name : "instructblip-vicuna-7b"
### LLM specification
checkpoint_path : checkpoints/instructBlip-7b/checkpoint-3950
max_new_tokens : 20
top_p : 0.95
repetition_penalty : 1.0
temperature : 0.0  # 0.0 means greedy decoding
length_penalty : 1.0
sampling_times : 1
retry_thres : 10

### Dataset specification
num_options : 6
is_sub : True
dataset : "mini-imagenet_image_heavy"
sample : 'origin'

### Inference specification
device : "cuda"
num_workers : 8

tag : "ft-trail1"
output_dir : "outputs/"