# model_name : "instructblip-vicuna-7b"
#model_name : "llava-v1.6-vicuna-7b" 
#model_name : "llava-1.5-7b"

### LLM specification
max_new_tokens : 10
top_p : 0.95
repetition_penalty : 1.2
temperature : 0.0  # 0.0 means greedy decoding
length_penalty : 1.0
sampling_times : 1
retry_thres : 2
device : cuda

### Dataset specification
#batch_size : 2
dataset : "mini-imagenet_image_heavy"

### Inference specification
num_workers : 24

#tag : "_ICL_Repeat_Image_2-shot"
output_dir : "outputs/"