max_new_tokens : 10
top_p : 0.95
repetition_penalty : 1.2
temperature : 0.0  # 0.0 means greedy decoding
length_penalty : 1.0
sampling_times : 1
retry_thres : 2
device : cuda

### Dataset specification
dataset : "seed-bench-img_VQA"

### Inference specification
num_workers : 16

output_dir : "outputs/"